- hosts: ec2_instance
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Docker image pull
      command: docker pull "${{ secrets.DOCKER_USERNAME }}/app:latest"
      
    - name: Run Docker container
      command: docker run -itd -p 8080:8080 app


