- hosts: ec2_instance
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build Docker image
      command: docker build -t app .

    - name: Run Docker container
      command: docker run -itd -p 8080:8080 app


