name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
     
      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test
        
      - name: Set up EC2 private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          #ssh-add private_key.pem
          
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy Docker container using Ansible
        run: |
          chmod 600 septkey.pem
          ansible-playbook -i inventory playbook.yml
        env:
          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.EC2_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: 'False'
      
